[package]
name = "tui-rs-file-dialog"
version = "0.1.0"
edition = "2021"
authors = ["Philipp Krones <hello@philkrones.com>"]

[[example]]
name = "demo"

[dependencies]
crossterm = "0.26.1"
tui = "0.19.0"
